[package]
name = "wasi-http-proxy-tests"
version = "0.0.0"
readme = "README.md"
edition = "2021"
publish = false

[lib]
crate-type=["cdylib"]

[dependencies]
wit-bindgen = { workspace = true, features = ["macros", "realloc"] }
