[package]
name = "test-programs"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition.workspace = true
publish = false
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
anyhow = { workspace = true }
wasi = "0.11.0"
wit-bindgen = { workspace = true, features = ['default'] }
libc = { workspace = true }
getrandom = "0.2.9"
